//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BsoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.DetalleCompra = new HashSet<DetalleCompra>();
        }


        [Display(Name = "Compra")]
        public int idCompra { get; set; }

        [Required(ErrorMessage = "Fecha de Compra - Campo obligatorio")]
        [Display(Name = "Fecha de Campra")]
        public System.DateTime fechaCompra { get; set; }

        [Required(ErrorMessage = "Nro de Comprobante - Campo obligatorio")]
        [StringLength(15)]
        [Display(Name = "Nro de Comprobante")]
        public string nroComprobante { get; set; }

        [Required(ErrorMessage = "Estado - Campo obligatorio")]
        [StringLength(45)]
        [Display(Name = "Estado")]
        public string estado { get; set; }

        [Required(ErrorMessage = "Campo obligatorio - Fecha de registro")]
        [Display(Name = "Fecha de Registro")]
        public System.DateTime fechaRegistro { get; set; }

        [Display(Name = "Proveedor")]
        public int idProveedor { get; set; }

        [Display(Name = "Usuario")]
        public int idUsuario { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
    }
}
