//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BsoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PerfilUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PerfilUsuario()
        {
            this.Usuario = new HashSet<Usuario>();
        }
       
        public int idPerfilUsuario { get; set; }

        [Required(ErrorMessage = "Campo obligatorio - Descripcion")]
        [StringLength(45)]
        [Display(Name = "Descripcion")]
        public string descripcion { get; set; }

        [Required(ErrorMessage = "Campo obligatorio - Estado")]
        [Display(Name = "Estado")]
        public string estado { get; set; }

        [Required(ErrorMessage = "Campo obligatorio - Fecha de registro")]
        [Display(Name = "Fecha de Registro")]
        public System.DateTime fechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
