//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BsoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Compra = new HashSet<Compra>();
            this.TecnicoProveedor = new HashSet<TecnicoProveedor>();
        }
    
        public int idProveedor { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [StringLength(100)]
        [Display(Name = "Razon Social")]
        public string razonSocial { get; set; }

        public string cuit { get; set; }

        public string domicilio { get; set; }

        public string telefono { get; set; }

        public string celular { get; set; }

        public string email { get; set; }

        public string estado { get; set; }

        public System.DateTime fechaRegistro { get; set; }

        public int idLocalidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual Localidad Localidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TecnicoProveedor> TecnicoProveedor { get; set; }
    }
}
