//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BsoftWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra
    {
        public int idCompra { get; set; }
        public int idEquipamiento { get; set; }
        public int cantidad { get; set; }
        public int plazoEntrega { get; set; }
        public System.DateTime fechaEntrega { get; set; }
        public int calidad { get; set; }
        public string observaciones { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Equipamiento Equipamiento { get; set; }
    }
}
